### PR TITLE
Fix URL for application/widget media type registration

### PR DESCRIPTION
**Pull request by jwilk**

### CODE REVIEW

**Comment by vfaronov** [comment]
Thanks for spotting this.

This URL is taken from the [IANA media types registry](http://www.iana.org/assignments/media-types/media-types.xml). Would you mind contacting them and asking them to fix the problem?

A few months ago I emailed iana@iana.org about a similar problem (`application/json` referred to RFC 7158, not 7159 as it should) and they fixed it promptly.

By the way, seems like the title of that link (“ISO/IEC 19757-2:2003/FDAM-1”) is also wrong — maybe they can fix it as well.

If IANA fixes the errors, my [sync tool](https://github.com/vfaronov/httpolice/blob/master/tools/iana.py) will pick it up before the next HTTPolice release, so no need for the PR.

If, however, IANA doesn’t fix the errors, then this PR will also need to add `'_no_sync': ['_citations']` to the data for `application/widget`, so that the sync tool doesn’t complain about the mismatch.

**Comment by jwilk** [comment]
I've poked IANA.
Let's see what happens.

**Comment by vfaronov** [comment]
Thanks! I did the same just a few hours before :)

**Comment by vfaronov** [comment]
They fixed it.

**Pull request closed without merging**
